import React, { createContext, useContext, useState, useEffect, type ReactNode } from 'react';

type Language = 'it' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const automaticTranslations: Record<string, string> = {
  'ZEPH PER DESIGN': 'ZEPH BY DESIGN',
  "Giochiamo a Minecraft, urliamo nei canali vocali e ogni tanto costruiamo cose che non prendono subito fuoco. Benvenuti nell'angolo più rumoroso di internet.": "We play Minecraft, scream in voice channels and sometimes build things that don't immediately catch fire. Welcome to the loudest corner of the internet.",
  'ENTRA SU DISCORD': 'JOIN DISCORD',
  'LEGGI LA WIKI': 'READ THE WIKI',
  'Membri in crew': 'Crew members',
  'Server & lore': 'Server & lore',
  'Creator chaos': 'Creator chaos',
  'CREW SPOTLIGHT': 'CREW SPOTLIGHT',
  'IN DIRETTA': 'LIVE',
  'Crew hub': 'Crew hub',
  'Scopri membri, creator e staff della community.': 'Discover members, creators and community staff.',
  'PvP ranking': 'PvP ranking',
  'Filtra discipline, rank e player della leaderboard.': 'Filter disciplines, ranks and leaderboard players.',
  'Broski labs': 'Broski labs',
  'Progetti': 'Projects',
  'Server, wiki, tool, mod e idee della community.': 'Servers, wiki, tools, mods and community ideas.',
  'LA COMMUNITY': 'THE COMMUNITY',
  'La Community': 'The Community',
  'Broski Community è un gruppo di giocatori italiani uniti dalla passione per Minecraft e dai contenuti caotici che produciamo insieme. Siamo una community aperta dove tutti possono unirsi, partecipare e contribuire alle varie attività che organizziamo.': 'Broski Community is a group of Italian players united by their passion for Minecraft and the chaotic content we create together. We are an open community where everyone can join, participate and contribute to the activities we organize.',
  'Il cuore della community. Canali vocali attivi 24/7, eventi, annunci e dove tutto inizia.': 'The heart of the community. Voice channels active 24/7, events, announcements and where everything begins.',
  'Il nostro server Minecraft anarchico dove i creator registrano i loro contenuti più iconici.': 'Our anarchic Minecraft server where creators record their most iconic content.',
  'Classifiche competitive in 11 categorie PvP diverse. HT (High Tier) e LT (Low Tier).': 'Competitive rankings across 11 different PvP categories. HT (High Tier) and LT (Low Tier).',
  'Come Unirsi': 'How to Join',
  'Entra nel nostro': 'Join our',
  'Presentati nel canale dedicato e leggi le regole': 'Introduce yourself in the dedicated channel and read the rules',
  'Partecipa attivamente alle discussioni e agli eventi': 'Actively participate in discussions and events',
  'Se sei un creator, contatta lo staff per possibili collaborazioni': 'If you are a creator, contact the staff for possible collaborations',
  '??? SMP è il server Minecraft che ha dato vita alla Broski Community. Un server anarchico dove i creator registrano i loro contenuti, creano lore e costruiscono progetti epici (che a volte prendono fuoco).': '??? SMP is the Minecraft server that gave life to the Broski Community. An anarchic server where creators record their content, create lore and build epic projects (that sometimes catch fire).',
  'Caratteristiche': 'Features',
  'Server Java Edition': 'Java Edition server',
  'Modalità Survival': 'Survival mode',
  'Eventi stagionali': 'Seasonal events',
  'Integrazione con YouTuber': 'YouTuber integration',
  'Regole Base': 'Basic Rules',
  'No hacking o client modificati': 'No hacking or modified clients',
  'Rispetta il lore esistente': 'Respect the existing lore',
  'Collabora con la community': 'Collaborate with the community',
  'Diventa un creator per accedere': 'Become a creator to access',
  'Stato Attuale': 'Current Status',
  'Season 0 - Il server è attualmente in fase di preparazione per la nuova stagione. Resta aggiornato sui canali Discord per le date di apertura.': 'Season 0 - The server is currently being prepared for the new season. Stay updated on Discord channels for opening dates.',
  'La Broski Tier List è il sistema di ranking competitivo della community. I giocatori vengono classificati in base alle loro abilità PvP in 11 categorie diverse.': 'The Broski Tier List is the community competitive ranking system. Players are ranked based on their PvP skills across 11 different categories.',
  'I migliori giocatori, divisi in 5 livelli:': 'The best players, divided into 5 levels:',
  'Giocatori in sviluppo, divisi in 5 livelli:': 'Developing players, divided into 5 levels:',
  'Titoli speciali basati sui punti totali:': 'Special titles based on total points:',
  'Le 11 Categorie': 'The 11 Categories',
  'Vai alla Tier List': 'Go to the Tier List',
  'I Creator': 'Creators',
  'La Broski Community è composta da diversi content creator che producono video su YouTube e streaming su Twitch, portando la lore di ??? SMP e le attività della community a un pubblico sempre più vasto.': 'The Broski Community includes several content creators who produce YouTube videos and Twitch streams, bringing ??? SMP lore and community activities to a wider audience.',
  'I creator pubblicano video sulle loro avventure in ??? SMP, eventi della community, e serie Minecraft collaborative.': 'Creators publish videos about their ??? SMP adventures, community events and collaborative Minecraft series.',
  'Streaming live di gameplay, interazioni con la community e eventi speciali in diretta.': 'Live gameplay streams, community interactions and special live events.',
  'Collaborazioni': 'Collaborations',
  'Eventi cross-creator, video collaborativi e progetti comuni che arricchiscono il contenuto della community.': 'Cross-creator events, collaborative videos and shared projects that enrich community content.',
  'Vuoi Diventare un Creator Broski?': 'Want to Become a Broski Creator?',
  "Se hai un canale YouTube o Twitch e ti interessa unirti ai creator ufficiali, entra nel Discord e contatta lo staff. Valutiamo collaborazioni con creator che condividono la nostra passione per Minecraft e l'intrattenimento caotico.": 'If you have a YouTube or Twitch channel and want to join the official creators, join Discord and contact the staff. We evaluate collaborations with creators who share our passion for Minecraft and chaotic entertainment.',
  'Unisciti a Noi': 'Join Us',
  'La Broski Community aspetta solo te. Entra nel Discord, esplora la Tier List, segui i creator e divertiti con noi!': 'The Broski Community is waiting for you. Join Discord, explore the Tier List, follow the creators and have fun with us!',
  'Entra nel Discord': 'Join Discord',
  'Esplora la Community': 'Explore the Community',
  'REGISTRATI': 'SIGN UP',
  'Unisciti alla Broski Community': 'Join the Broski Community',
  'Geometry Dash Username (opzionale ma consigliato)': 'Geometry Dash Username (optional but recommended)',
  'Minimo 6 caratteri': 'Minimum 6 characters',
  'Conferma Password *': 'Confirm Password *',
  'Ripeti la password': 'Repeat password',
  'Creando account...': 'Creating account...',
  'CREA ACCOUNT': 'CREATE ACCOUNT',
  'Hai già un account?': 'Already have an account?',
  'ACCEDI': 'LOGIN',
};

const normalizeText = (text: string) => text.replace(/\s+/g, ' ').trim();

const translations = {
  it: {
    // Header / Navigation
    'nav.home': 'Home',
    'nav.tierlist': 'TierList',
    'nav.projects': 'Progetti',
    'nav.social': 'Social',
    'nav.wiki': 'Wiki',
    'nav.login': 'Accedi',
    'nav.logout': 'Esci',
    'nav.profile': 'Profilo',
    'nav.admin': 'Admin',
    'nav.language': 'Lingua',
    'nav.italian': 'Italiano',
    'nav.english': 'Inglese',

    // Hero Section
    'hero.welcome': 'Benvenuto nella',
    'hero.community': 'Community',
    'hero.badge': 'ZEPH PER DESIGN',
    'hero.subtitle': "Giochiamo a Minecraft, urliamo nei canali vocali e ogni tanto costruiamo cose che non prendono subito fuoco. Benvenuti nell'angolo più rumoroso di internet.",
    'hero.cta.primary': 'Esplora la TierList',
    'hero.cta.secondary': 'Scopri di più',
    'hero.cta.discord': 'ENTRA SU DISCORD',
    'hero.cta.wiki': 'LEGGI LA WIKI',
    'hero.stats.crew': 'Membri in crew',
    'hero.stats.server': 'Server & lore',
    'hero.stats.chaos': 'Creator chaos',
    'hero.spotlight': 'CREW SPOTLIGHT',
    'hero.live': 'IN DIRETTA',
    'hero.render.waiting': 'In attesa del render di',
    'hero.members': 'Membri Attivi',
    'hero.events': 'Eventi Mensili',
    'hero.prizes': 'Premi Distribuiti',

    // Home
    'home.social.subtitle': 'Crew hub',
    'home.social.title': 'Social',
    'home.social.description': 'Scopri membri, creator e staff della community.',
    'home.tierlist.subtitle': 'PvP ranking',
    'home.tierlist.title': 'Tier List',
    'home.tierlist.description': 'Filtra discipline, rank e player della leaderboard.',
    'home.projects.subtitle': 'Broski labs',
    'home.projects.title': 'Progetti',
    'home.projects.description': 'Server, wiki, tool, mod e idee della community.',

    // SignUp
    'signup.title': 'REGISTRATI',
    'signup.subtitle': 'Unisciti alla Broski Community',
    'signup.minecraft_username': 'Minecraft Username',
    'signup.gd_username': 'Geometry Dash Username',
    'signup.gd_optional': 'opzionale ma consigliato',
    'signup.email': 'Email',
    'signup.password': 'Password',
    'signup.password_placeholder': 'Minimo 6 caratteri',
    'signup.confirm_password': 'Conferma Password',
    'signup.confirm_password_placeholder': 'Ripeti la password',
    'signup.error.password_mismatch': 'Le password non coincidono.',
    'signup.error.password_length': 'La password deve essere di almeno 6 caratteri.',
    'signup.creating': 'Creando account...',
    'signup.create_account': 'CREA ACCOUNT',
    'signup.have_account': 'Hai già un account?',
    'signup.login': 'ACCEDI',

    // Features
    'features.title': 'Perché unirti a noi?',
    'features.section.title': 'COSA SUCCEDE',
    'features.section.desc': 'Una rotazione di caos ???lato: costruzioni, eventi, community, PvP e tutte le cose che rendono Broski impossibile da ignorare.',
    'features.meet_members': 'Incontra i Membri',
    'features.number.building': 'COSTRUZIONE',
    'features.number.chaos': 'CAOS',
    'features.number.events': 'EVENTI',
    'features.number.future': 'FUTURO',
    'features.building.title': 'Architettura su Minecraft',
    'features.building.desc': "Non costruiamo solo capanne di terra. Costruiamo enormi monoliti che fanno crashare i server, di dubbia integrità strutturale. Unisciti al team di costruzione o guardaci semplicemente detonare TNT per sbaglio vicino allo spawn.",
    'features.chaos.title': 'Comicità Senza Filtri',
    'features.chaos.desc': 'Chiamate vocali a tarda notte che degenerano nella follia assoluta. Prendiamo i nostri giochi abbastanza sul serio, ma noi stessi per niente. Porta una pelle dura e un microfono rotto.',
    'features.friendship.title': 'Amicizia Forzata',
    'features.friendship.desc': 'Alla fine della giornata, Broski riguarda le persone. Persone terribilmente rumorose, geograficamente sparse e bizzarramente leali. Siamo una famiglia, anche se altamente disfunzionale.',
    'features.pvp.title': 'Combattimento Estremo',
    'features.pvp.desc': "Sfide all'ultimo sangue nell'arena.",
    'features.events.title': 'Tornei Mensili',
    'features.events.desc': 'Competizioni con premi reali e gloria eterna.',
    'features.streaming.title': 'Live Non-Stop',
    'features.streaming.desc': 'Segui le nostre avventure in diretta su Twitch.',
    'features.modding.title': 'Server Moddati',
    'features.modding.desc': 'Oltre il vanilla, esploriamo nuovi mondi.',
    'features.discord.title': 'Chat Attiva',
    'features.discord.desc': 'Il nostro quartier generale per il coordinamento.',
    'features.redstone.title': 'Ingegneria Folle',
    'features.redstone.desc': 'Circuiti complessi che nessuno capisce.',
    'features.survival.title': 'Sopravvivenza Hardcore',
    'features.survival.desc': 'Una sola vita, mille modi per perderla.',
    'features.creative.title': 'Libertà Totale',
    'features.creative.desc': 'Esprimi la tua creatività senza limiti.',
    'features.lore.title': 'Storia del Gruppo',
    'features.lore.desc': 'Anni di meme e momenti indimenticabili.',
    'features.future.title': 'Nuovi Progetti',
    'features.future.desc': 'Quello che stiamo preparando per voi.',
    'features.competitive.title': 'Competitivo',
    'features.competitive.desc': 'Partecipa a tornei e eventi con i migliori giocatori. Dimostra il tuo valore e scala le classifiche.',
    'features.community.title': 'Community',
    'features.community.desc': 'Unisciti a una community attiva e appassionata. Trova nuovi amici e rivali con cui giocare.',
    'features.rewards.title': 'Ricompense',
    'features.rewards.desc': 'Vinci premi esclusivi e riconoscimenti per le tue performance. Ogni vittoria conta.',

    // TierList Page
    'tierlist.title': 'TierList Competitiva',
    'tierlist.subtitle': 'Classifica dei migliori giocatori per categoria',
    'tierlist.category.overall': 'Generale',
    'tierlist.category.ltms': 'LTMs',
    'tierlist.category.vanilla': 'Vanilla',
    'tierlist.category.uhc': 'UHC',
    'tierlist.category.pot': 'Pot PvP',
    'tierlist.category.nethop': 'Netherite Hop',
    'tierlist.category.smp': 'SMP',
    'tierlist.category.sword': 'Spada',
    'tierlist.category.axe': 'Ascia',
    'tierlist.category.mace': 'Mazza',
    'tierlist.category.crystal': 'Crystal',
    'tierlist.rank': 'Rank',
    'tierlist.player': 'Giocatore',
    'tierlist.points': 'Punti',
    'tierlist.region': 'Regione',
    'tierlist.tier.ht1': 'HT1 - Elite',
    'tierlist.tier.lt1': 'LT1 - Pro',
    'tierlist.tier.ht2': 'HT2 - Avanzato',
    'tierlist.tier.lt2': 'LT2 - Intermedio',
    'tierlist.tier.ht3': 'HT3 - Base',
    'tierlist.tier.lt3': 'LT3 - Principiante',
    'tierlist.tier.ht4': 'HT4 - Novizio',
    'tierlist.tier.lt4': 'LT4 - Apprendista',
    'tierlist.tier.ht5': 'HT5 - Rookie',
    'tierlist.tier.lt5': 'LT5 - Newbie',
    'tierlist.tier.unranked': 'Non Classificato',
    'tierlist.loading': 'Caricamento...',
    'tierlist.empty': 'Nessun giocatore in questa categoria',
    'tierlist.empty.hint': 'Prova un altro filtro oppure torna alla classifica globale per vedere tutti i player disponibili.',
    'tierlist.stats.total': 'Giocatori Totali',
    'tierlist.stats.top': 'Top Tier',
    'tierlist.stats.avg': 'Media Punti',
    'tierlist.cta.leaderboard': 'Esplora',
    'tierlist.filter.mode': 'Modalità di ranking',
    'tierlist.filter.choose': 'Scegli categoria',
    'tierlist.filter.hint': 'Scorri orizzontalmente, cambia disciplina e la classifica si riordina subito per tier e punti.',
    'tierlist.leaderboard.active': 'Leaderboard attiva',

    // Projects Page
    'projects.title': 'I Nostri Progetti',
    'projects.subtitle': 'Scopri le iniziative e i contenuti della community',
    'projects.youtube.title': 'YouTube Channel',
    'projects.youtube.desc': 'Iscriviti al nostro canale per video, tutorial e highlight delle competizioni.',
    'projects.twitch.title': 'Twitch Live',
    'projects.twitch.desc': 'Segui le nostre live streaming con eventi in diretta e interazione con la community.',
    'projects.discord.title': 'Server Discord',
    'projects.discord.desc': 'Entra nel nostro server Discord per chattare, trovare team e partecipare agli eventi.',
    'projects.tiktok.title': 'TikTok',
    'projects.tiktok.desc': 'Guarda i nostri short video con clip divertenti e momenti epici.',
    'projects.visit': 'Visita',
    'projects.subscribe': 'Iscriviti',
    'projects.join': 'Unisciti',
    'projects.follow': 'Segui',
    'projects.hero.badge': 'BROSKI LABS',
    'projects.hero.stat.server': 'Server & SMP',
    'projects.controlsmp.featured': 'FEATURED',
    'projects.controlsmp.status': 'OFFLINE - SEASONS 0',
    'projects.controlsmp.desc': 'Il nostro progetto principale ispirato alla serie degli YouTuber, con eventi e lore creata dalla community. Costruisci, sopravvivi, tradisci.',
    'projects.controlsmp.countdown': 'VAI AL COUNTDOWN',
    'projects.controlsmp.map': 'MAPPA SOON',
    'projects.wiki.title': 'Broski Wiki',
    'projects.wiki.desc': "L'enciclopedia ufficiale dei Broski dove documentiamo ogni evento, membro e pazzia avvenuta nel server.",
    'projects.wiki.progress': '100% COMPLETATA',
    'projects.wiki.cta': 'LEGGI LA WIKI',
    'projects.tools.title': 'Broski Projects',
    'projects.tools.desc': 'Una collezione di tool, siti web e mod create dai membri per migliorare l\'esperienza di gioco.',
    'projects.tools.repo': 'ESPLORA REPO',
    'projects.tools.mods': 'DOWNLOAD MODS',
    'projects.idea.badge': 'OPEN CALL',
    'projects.idea.title': 'Hai un\'idea folle?',
    'projects.idea.desc': 'Siamo sempre alla ricerca di nuovi progetti da integrare nell\'ecosistema Broski. Proponi la tua idea nella pagina dedicata.',
    'projects.idea.cta': 'PROPONI',

    // Social Page
    'social.title': 'La Nostra Crew',
    'social.subtitle': 'Conosci i membri e lo staff della community',
    'social.filter.all': 'Tutti',
    'social.filter.founder': 'Founder',
    'social.filter.cofounder': 'Co-Founder',
    'social.filter.admin': 'Admin',
    'social.filter.mod': 'Mod',
    'social.member': 'Membro',
    'social.rank': 'Rank',
    'social.discord': 'Discord',
    'social.youtube': 'YouTube',
    'social.twitch': 'Twitch',
    'social.description': 'Descrizione',
    'social.status.online': 'Online',
    'social.status.offline': 'Offline',
    'social.info': 'INFO',
    'social.close': 'CHIUDI',
    'social.crew.active': 'Crew Attiva',
    'social.channels': 'Canali YouTube',
    'social.streamers': 'Streamer Twitch',
    'social.card.member': 'Scheda membro',
    'social.card.whois': 'Chi è {name}?',
    'social.card.links': 'link',
    'social.card.social': 'Social',
    'social.card.status': 'Status',
    'social.render.3d': 'RENDER 3D',
    'social.render.live': 'LIVE',
    'social.roster.selected': 'Roster selezionato',
    'social.roster.all': 'Tutta la crew',
    'social.roster.hint': 'Tocca una card per aprire il dossier completo. I pulsanti social restano sempre raggiungibili senza aprire il pannello.',

    // Wiki Page
    'wiki.title': 'Knowledge Base',
    'wiki.subtitle': 'Guide, tutorial e informazioni sulla community',
    'wiki.hero.badge': 'DOCUMENTAZIONE UFFICIALE',
    'wiki.hero.description': "Benvenuto nella documentazione ufficiale della Broski Community. Qui trovi tutto quello che c'è da sapere su ??? SMP, la Tier List, i nostri creator e come far parte della community.",
    'wiki.nav.community': 'La Community',
    'wiki.nav.smp': '??? SMP',
    'wiki.nav.tierlist': 'Tier List',
    'wiki.nav.creators': 'I Creator',
    'wiki.nav.faq': 'FAQ',
    'wiki.search.placeholder': 'Cerca nella wiki...',
    'wiki.category.gettingstarted': 'Inizio',
    'wiki.category.rules': 'Regole',
    'wiki.category.pvp': 'PvP',
    'wiki.category.faq': 'FAQ',
    'wiki.category.all': 'Tutte le Categorie',
    'wiki.article.read': 'Leggi',
    'wiki.article.minutes': 'min di lettura',
    'wiki.empty': 'Nessun articolo trovato',
    'wiki.back': 'Torna alla Wiki',
    'wiki.lastupdated': 'Ultimo aggiornamento',

    // Wiki Content
    'wiki.community.title': 'La Community',
    'wiki.community.intro': 'è un gruppo di giocatori italiani uniti dalla passione per Minecraft e dai contenuti caotici che produciamo insieme. Siamo una community aperta dove tutti possono unirsi, partecipare e contribuire alle varie attività che organizziamo.',
    'wiki.community.discord.desc': 'Il cuore della community. Canali vocali attivi 24/7, eventi, annunci e dove tutto inizia.',
    'wiki.community.smp.desc': 'Il nostro server Minecraft anarchico dove i creator registrano i loro contenuti più iconici.',
    'wiki.community.tierlist.desc': 'Classifiche competitive in 11 categorie PvP diverse. HT (High Tier) e LT (Low Tier).',
    'wiki.community.join.title': 'Come Unirsi',
    'wiki.community.join.step1': 'Entra nel nostro',
    'wiki.community.join.step2': 'Presentati nel canale dedicato e leggi le regole',
    'wiki.community.join.step3': 'Partecipa attivamente alle discussioni e agli eventi',
    'wiki.community.join.step4': 'Se sei un creator, contatta lo staff per possibili collaborazioni',
    'wiki.smp.title': '??? SMP',
    'wiki.smp.intro': 'è il server Minecraft che ha dato vita alla Broski Community. Un server anarchico dove i creator registrano i loro contenuti, creano lore e costruiscono progetti epici (che a volte prendono fuoco).',
    'wiki.smp.features.title': 'Caratteristiche',
    'wiki.smp.features.java': 'Server Java Edition',
    'wiki.smp.features.survival': 'Modalità Survival',
    'wiki.smp.features.events': 'Eventi stagionali',
    'wiki.smp.features.youtube': 'Integrazione con YouTuber',
    'wiki.smp.rules.title': 'Regole Base',
    'wiki.smp.rules.nohack': 'No hacking o client modificati',
    'wiki.smp.rules.lore': 'Rispetta il lore esistente',
    'wiki.smp.rules.collab': 'Collabora con la community',
    'wiki.smp.rules.creator': 'Diventa un creator per accedere',
    'wiki.smp.status.title': 'Stato Attuale',
    'wiki.smp.status.desc': 'Season 0 - Il server è attualmente in fase di preparazione per la nuova stagione. Resta aggiornato sui canali Discord per le date di apertura.',
    'wiki.tierlist.intro': 'è il sistema di ranking competitivo della community. I giocatori vengono classificati in base alle loro abilità PvP in 11 categorie diverse.',
    'wiki.tierlist.ht.desc': 'I migliori giocatori, divisi in 5 livelli:',
    'wiki.tierlist.lt.desc': 'Giocatori in sviluppo, divisi in 5 livelli:',
    'wiki.tierlist.combatrank.desc': 'Titoli speciali basati sui punti totali:',
    'wiki.tierlist.categories.title': 'Le 11 Categorie',
    'wiki.tierlist.cta': 'Vai alla Tier List',
    'wiki.creators.title': 'I Creator',
    'wiki.creators.intro': 'La Broski Community è composta da diversi content creator che producono video su YouTube e streaming su Twitch, portando la lore di ??? SMP e le attività della community a un pubblico sempre più vasto.',
    'wiki.creators.youtube.desc': 'I creator pubblicano video sulle loro avventure in ??? SMP, eventi della community, e serie Minecraft collaborative.',
    'wiki.creators.twitch.desc': 'Streaming live di gameplay, interazioni con la community e eventi speciali in diretta.',
    'wiki.creators.collab.title': 'Collaborazioni',
    'wiki.creators.collab.desc': 'Eventi cross-creator, video collaborativi e progetti comuni che arricchiscono il contenuto della community.',
    'wiki.creators.join.title': 'Vuoi Diventare un Creator Broski?',
    'wiki.creators.join.desc': "Se hai un canale YouTube o Twitch e ti interessa unirti ai creator ufficiali, entra nel Discord e contatta lo staff. Valutiamo collaborazioni con creator che condividono la nostra passione per Minecraft e l'intrattenimento caotico.",
    'wiki.faq.title': 'FAQ',
    'wiki.faq.q1': 'Come posso unirmi alla community?',
    'wiki.faq.a1': 'Entra nel nostro Discord ufficiale, presentati nel canale dedicato e inizia a partecipare attivamente. La community è aperta a tutti i giocatori Minecraft italiani.',
    'wiki.faq.q2': '??? SMP è accessibile a tutti?',
    'wiki.faq.a2': 'No, ??? SMP è un server riservato ai creator ufficiali della community. Tuttavia, organizziamo eventi aperti anche agli altri membri della community.',
    'wiki.faq.q3': 'Come funziona la Tier List?',
    'wiki.faq.a3': "La Tier List classifica i giocatori in 11 categorie PvP. Ogni categoria ha rank HT (High Tier, blu) e LT (Low Tier, rossi). L'OVERALL è calcolato automaticamente come media degli altri rank.",
    'wiki.faq.q4': 'Posso proporre modifiche al sito?',
    'wiki.faq.a4': 'Certo! Siamo sempre aperti a suggerimenti. Contatta un admin nel Discord o usa i canali dedicati ai feedback.',
    'wiki.faq.q5': 'Come vengono assegnati i punti nella Tier List?',
    'wiki.faq.a5': 'I punti dipendono dal tier: HT1/LT1 = 45-60 pts, HT2/LT2 = 20-30 pts, HT3/LT3 = 6-10 pts, HT4/LT4 = 3-4 pts, HT5/LT5 = 1-2 pts.',
    'wiki.faq.q6': "C'è un minimo di età per entrare?",
    'wiki.faq.a6': 'Non abbiamo un limite di età rigido, ma richiediamo maturità e rispetto delle regole della community. Il comportamento è più importante dell\'età.',
    'wiki.cta.title': 'Unisciti a Noi',
    'wiki.cta.desc': 'La Broski Community aspetta solo te. Entra nel Discord, esplora la Tier List, segui i creator e divertiti con noi!',
    'wiki.cta.discord': 'Entra nel Discord',
    'wiki.cta.community': 'Esplora la Community',

    // Login/Auth
    'auth.login.title': 'Accedi',
    'auth.login.subtitle': 'Entra con il tuo account Broski',
    'auth.login.discord': 'Accedi con Discord',
    'auth.login.google': 'Accedi con Google',
    'auth.login.or': 'oppure',
    'auth.login.email': 'Email',
    'auth.login.password': 'Password',
    'auth.login.remember': 'Ricordami',
    'auth.login.forgot': 'Password dimenticata?',
    'auth.login.button': 'Accedi',
    'auth.login.noaccount': 'Non hai un account?',
    'auth.login.register': 'Registrati',
    'auth.logout.confirm': 'Sei sicuro di voler uscire?',
    'auth.logout.yes': 'Sì, esci',
    'auth.logout.no': 'Annulla',

    // SignIn
    'signin.title': 'ACCEDI',
    'signin.subtitle': 'Entra nel tuo account Broski',
    'signin.identifier': 'Username o Email',
    'signin.identifier_placeholder': 'es. Steve o steve@email.com',
    'signin.password': 'Password',
    'signin.password_placeholder': 'La tua password',
    'signin.loading': 'Caricamento...',
    'signin.button': 'ACCEDI',
    'signin.or': 'Oppure',
    'signin.create_account': 'CREA ACCOUNT',

    // UnstableSmp
    'smp.badge': 'SERVER FEATURED',
    'smp.description': 'La rivoluzione. Vai a guardare i video dei nostri content creator qui sotto!',
    'smp.countdown_info': 'Countdown e apertura stagione appena disponibili',
    'smp.goto_countdown': 'VAI AL COUNTDOWN',
    'smp.of_control': 'DELLA ??? SMP',

    // Countdown
    'countdown.title': 'COUNTDOWN',
    'countdown.days': 'GIORNI',
    'countdown.hours': 'ORE',
    'countdown.minutes': 'MINUTI',
    'countdown.seconds': 'SECONDI',
    'countdown.launched': 'LANCIATO!',
    'countdown.finished': 'La stagione è iniziata! Ci vediamo nel server.',
    'countdown.mute': 'MUTA',
    'countdown.unmute': 'ATTIVA SUONO',

    // Idols
    'idols.badge': 'DALLE NOSTRE SMP',
    'idols.title': 'CREATOR WALL',
    'idols.description': 'Video, momenti epici e creator che alimentano l\'hype: entra nei canali e recupera l\'ultimo video di ognuno!',
    'idols.creator': 'CREATOR',
    'idols.latest_video': 'Ultimo Video:',
    'idols.watch_video': 'ULTIMO VIDEO',

    // Footer
    'footer.rights': 'Tutti i diritti riservati',
    'footer.made': 'Fatto con',
    'footer.by': 'dalla community Broski',
    'footer.links': 'Link Utili',
    'footer.contact': 'Contatti',
    'footer.legal': 'Legale',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Termini di Servizio',
    'footer.disclaimer': 'NON È UN PRODOTTO UFFICIALE MINECRAFT.',

    // Common
    'common.loading': 'Caricamento...',
    'common.error': 'Errore',
    'common.retry': 'Riprova',
    'common.save': 'Salva',
    'common.cancel': 'Annulla',
    'common.edit': 'Modifica',
    'common.delete': 'Elimina',
    'common.create': 'Crea',
    'common.search': 'Cerca',
    'common.filter': 'Filtra',
    'common.sort': 'Ordina',
    'common.apply': 'Applica',
    'common.reset': 'Reset',
    'common.yes': 'Sì',
    'common.no': 'No',
    'common.confirm': 'Conferma',
    'common.back': 'Indietro',
    'common.next': 'Avanti',
    'common.previous': 'Precedente',
    'common.submit': 'Invia',
    'common.close': 'Chiudi',
    'common.open': 'Apri',
    'common.more': 'Di più',
    'common.less': 'Di meno',
    'common.show': 'Mostra',
    'common.hide': 'Nascondi',
    'common.workingon': 'Stiamo lavorando a questa pagina!',
    'common.gohome': 'VAI ALLA HOME',

    // Admin Panel
    'admin.title': 'Pannello Admin',
    'admin.subtitle': 'Gestisci news, tierlist e giocatori',
    'admin.tab.news': 'NEWS',
    'admin.tab.tierlist': 'TIER LIST',
    'admin.news.title': 'Gestione News',
    'admin.news.new': 'NUOVA NEWS',
    'admin.news.edit': 'Modifica News',
    'admin.news.create': 'Nuova News',
    'admin.news.form.title': 'Titolo',
    'admin.news.form.category': 'Categoria',
    'admin.news.form.content': 'Contenuto',
    'admin.news.form.icon': 'Icona (Material Symbol)',
    'admin.news.form.variant': 'Variante',
    'admin.news.form.variant.default': 'Default',
    'admin.news.form.variant.urgent': 'Urgente (Blu)',
    'admin.news.form.variant.event': 'Evento (Secondario)',
    'admin.news.form.order': 'Ordine',
    'admin.news.form.active': 'Attiva',
    'admin.tierlist.title': 'Gestione TierList',
    'admin.tierlist.new': 'NUOVO PLAYER',
    'admin.tierlist.edit': 'Modifica Player',
    'admin.tierlist.create': 'Nuovo Player',
    'admin.tierlist.form.ign': 'Minecraft IGN',
    'admin.tierlist.form.region': 'Regione',
    'admin.tierlist.form.ranks': 'RANK PER CATEGORIA',
    'admin.tierlist.form.overall': 'OVERALL (auto)',
    'admin.tierlist.form.overall.desc': 'Calcolato dalla media di tutte le categorie',
    'admin.tierlist.points': 'punti',
    'admin.tierlist.combatrank': 'Combat Rank',
    'admin.tierlist.save': 'SALVA',
    'admin.tierlist.cancel': 'ANNULLA',
    'admin.players.title': 'Giocatori',
    'admin.players.search': 'Cerca giocatori...',
    'admin.players.edit': 'Modifica',
    'admin.players.delete': 'Elimina',
    'admin.save': 'Salva',
    'admin.cancel': 'Annulla',
    'admin.delete': 'Elimina',
    'admin.edit': 'Modifica',
    'admin.actions': 'Azioni',
    'admin.created': 'creato',
    'admin.updated': 'aggiornato',

    // 404 Page
    'notfound.message': 'Questa pagina non esiste... forse è stata eliminata, o forse non è mai esistita.',

    // Store
    'store.badge': 'BROSKI STORE',
    'store.title': 'MERCH IN ARRIVO',
    'store.description': 'Il merch ufficiale della Broski Community sta arrivando. Resta sintonizzato per hoodie, tee, accessori e molto altro.',
    'store.wip': 'Work in Progress',
    'store.wip.desc': 'Stiamo preparando qualcosa di speciale per voi.',
    'store.notify': 'Seguici su Discord per sapere quando apriamo!',
    'store.coming_soon': 'COMING SOON',
    'store.banner': 'Spedizione in tutta Europa • Qualità Premium • Design Esclusivi',

    // Mods
    'mods.badge': 'BROSKI MODS',
    'mods.title': 'MODS & PLUGINS',
    'mods.subtitle': 'Scarica mod e plugin creati dalla Broski Community.',
    'mods.publish': 'Pubblica',
    'mods.my_mods': 'LE MIE MOD',
    'mods.search': 'Cerca plugins...',
    'mods.sort_by': 'Sort by:',
    'mods.view': 'View:',
    'mods.results': 'risultati',
    'mods.no_results': 'Nessun risultato',
    'mods.no_results.hint': 'Prova a cambiare i filtri o la ricerca.',
    'mods.followed_creators': 'Followed',
    'mods.saved_projects': 'Saved',
    'mods.back': 'INDIETRO',
    'mods.projects': 'progetti',
    'mods.no_followed': 'Nessun creator seguito',
    'mods.no_followed_hint': 'Segui i creator dalla pagina dei loro progetti.',
    'mods.no_saved': 'Nessun progetto salvato',
    'mods.no_saved_hint': 'Salva i progetti che ti interessano dalla loro pagina.',
    'idea.back': 'TORNA AI PROGETTI',
    'idea.badge': 'IDEA FOLLE',
    'idea.title': 'PROPONI UN\'IDEA',
    'idea.subtitle': 'Hai un\'idea per la community? Scrivila qui e la leggeremo!',
    'idea.field.title': 'TITOLO DELL\'IDEA',
    'idea.field.title_placeholder': 'es. Torneo PvP mensile con premi',
    'idea.field.content': 'LA TUA IDEA',
    'idea.field.content_placeholder': 'Descrivi la tua idea in dettaglio...',
    'idea.field.rating': 'COM\'È STATA L\'ESPERIENZA?',
    'idea.field.rating_desc': 'Quanto ti è piaciuto proporre un\'idea? (1-5 stelle)',
    'idea.submit': 'INVIA IDEA',
    'idea.submitting': 'INVIO...',
    'idea.error.login': 'Devi essere loggato.',
    'idea.error.title': 'Il titolo è obbligatorio.',
    'idea.error.content': 'La descrizione è obbligatoria.',
    'idea.error.rating': 'Seleziona un rating.',
    'idea.success.title': 'Idea inviata!',
    'idea.success.desc': 'Grazie per il tuo contributo! Gli admin la leggeranno presto.',
    'nav.my_ideas': 'Le mie idee',
    'myideas.empty': 'Non hai ancora proposto idee',
    'myideas.submit_first': 'PROPONI LA TUA PRIMA IDEA',
    'mods.category': 'Category',
    'mods.game_version': 'Game version',
    'mods.loader': 'Loader',
    'mods.platform': 'Platform',
    'mods.show_all_versions': 'Show all versions',
    'mods.show_less': 'Mostra meno',
    'mods.upload.title': 'NUOVA MOD',
    'mods.upload.subtitle': 'Compila tutti i campi e invia in revisione. Un admin approverà la tua mod.',
    'mods.upload.info': 'Informazioni Base',
    'mods.upload.files': 'File',
    'mods.upload.jar': 'FILE .JAR',
    'mods.upload.jar.hint': 'Clicca per caricare il file .jar',
    'mods.upload.icon': 'ICONA',
    'mods.upload.icon.hint': "Clicca per caricare un'icona",
    'mods.upload.screenshots': 'SCREENSHOT',
    'mods.upload.screenshots.hint': 'Clicca per caricare screenshot',
    'mods.upload.submit': 'MANDA IN REVISIONE',
    'mods.upload.submitting': 'CARICAMENTO...',
    'mods.upload.note': 'La tua mod sarà visibile solo a te e agli admin fino all\'approvazione.',
    'mods.detail.description': 'Descrizione',
    'mods.detail.gallery': 'Galleria',
    'mods.detail.versions': 'Versioni',
    'mods.detail.download': 'Download',
    'mods.detail.downloading': 'Scaricando...',
    'mods.detail.compatibility': 'Compatibilità',
    'mods.detail.platforms': 'Piattaforme',
    'mods.detail.environments': 'Ambienti supportati',
    'mods.detail.tags': 'Tags',
    'mods.detail.creator': 'Creatore',
    'mods.detail.details': 'Dettagli',
    'mods.detail.published': 'Pubblicato',
    'mods.detail.updated': 'Aggiornato',
    'mods.detail.size': 'Dimensione',
    'mods.detail.not_found': 'Mod non trovata',
    'mods.detail.back': 'TORNA ALLE MODS',
    'mods.detail.no_screenshots': 'Nessuno screenshot disponibile.',
    'mods.my.title': 'LE MIE MOD',
    'mods.my.subtitle': 'Gestisci le tue mod e controlla lo stato di approvazione.',
    'mods.my.empty': 'Non hai ancora caricato nessuna mod.',
    'mods.my.first': 'CARICA LA TUA PRIMA MOD',
    'mods.status.pending': 'IN REVISIONE',
    'mods.status.approved': 'APPROVATA',
    'mods.status.rejected': 'RIFIUTATA',
    'mods.status.on_hold': 'IN ATTESA',

    // Contacts
    'contacts.badge': 'REACH OUT',
    'contacts.title': 'CONTATTI',
    'contacts.response_time': 'Tempi di Risposta',
    'contacts.response_desc': 'Rispondiamo generalmente entro 24-48 ore. Per questioni urgenti, il modo più veloce per raggiungerci è tramite Discord. Per collaborazioni o proposte, includi una breve descrizione del progetto.',

    // Auth Terms
    'auth.terms.title': 'ACCETTA I TERMINI',
    'auth.terms.subtitle': 'Per continuare devi accettare i nostri termini aggiornati.',
    'auth.terms.checkbox': 'Accetto i Termini di Servizio e la Privacy Policy della Broski Community.',
    'auth.terms.accept': 'ACCETTA E CONTINUA',
    'auth.terms.error': 'Devi accettare i Termini di Servizio e la Privacy Policy per continuare.',
    'auth.terms.signup_error': 'Devi accettare i Termini di Servizio e la Privacy Policy per registrarti.',
  },
  en: {
    // Header / Navigation
    'nav.home': 'Home',
    'nav.tierlist': 'TierList',
    'nav.projects': 'Projects',
    'nav.social': 'Social',
    'nav.wiki': 'Wiki',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    'nav.profile': 'Profile',
    'nav.admin': 'Admin',
    'nav.language': 'Language',
    'nav.italian': 'Italian',
    'nav.english': 'English',

    // Hero Section
    'hero.welcome': 'Welcome to',
    'hero.community': 'Community',
    'hero.badge': 'ZEPH BY DESIGN',
    'hero.subtitle': 'We play Minecraft, scream in voice channels and sometimes build things that don\'t immediately catch fire. Welcome to the loudest corner of the internet.',
    'hero.cta.primary': 'Explore TierList',
    'hero.cta.secondary': 'Learn More',
    'hero.cta.discord': 'JOIN DISCORD',
    'hero.cta.wiki': 'READ THE WIKI',
    'hero.stats.crew': 'Crew members',
    'hero.stats.server': 'Server & lore',
    'hero.stats.chaos': 'Creator chaos',
    'hero.spotlight': 'CREW SPOTLIGHT',
    'hero.live': 'LIVE',
    'hero.render.waiting': 'Waiting for render of',
    'hero.members': 'Active Members',
    'hero.events': 'Monthly Events',
    'hero.prizes': 'Prizes Distributed',

    // Home
    'home.social.subtitle': 'Crew hub',
    'home.social.title': 'Social',
    'home.social.description': 'Discover members, creators and community staff.',
    'home.tierlist.subtitle': 'PvP ranking',
    'home.tierlist.title': 'Tier List',
    'home.tierlist.description': 'Filter disciplines, ranks and leaderboard players.',
    'home.projects.subtitle': 'Broski labs',
    'home.projects.title': 'Projects',
    'home.projects.description': 'Servers, wiki, tools, mods and community ideas.',

    // SignUp
    'signup.title': 'SIGN UP',
    'signup.subtitle': 'Join the Broski Community',
    'signup.minecraft_username': 'Minecraft Username',
    'signup.gd_username': 'Geometry Dash Username',
    'signup.gd_optional': 'optional but recommended',
    'signup.email': 'Email',
    'signup.password': 'Password',
    'signup.password_placeholder': 'Minimum 6 characters',
    'signup.confirm_password': 'Confirm Password',
    'signup.confirm_password_placeholder': 'Repeat password',
    'signup.error.password_mismatch': 'Passwords do not match.',
    'signup.error.password_length': 'Password must be at least 6 characters.',
    'signup.creating': 'Creating account...',
    'signup.create_account': 'CREATE ACCOUNT',
    'signup.have_account': 'Already have an account?',
    'signup.login': 'LOGIN',

    // Features
    'features.title': 'Why join us?',
    'features.section.title': "WHAT'S HAPPENING",
    'features.section.desc': 'A rotation of controlled chaos: builds, events, community, PvP and everything that makes Broski impossible to ignore.',
    'features.meet_members': 'Meet the Members',
    'features.number.building': 'BUILDING',
    'features.number.chaos': 'CHAOS',
    'features.number.events': 'EVENTS',
    'features.number.future': 'FUTURE',
    'features.building.title': 'Minecraft Architecture',
    'features.building.desc': "We don't just build dirt huts. We build enormous monoliths that crash servers, of questionable structural integrity. Join the building team or just watch us accidentally detonate TNT near spawn.",
    'features.chaos.title': 'Unfiltered Comedy',
    'features.chaos.desc': 'Late night voice calls that devolve into absolute madness. We take our games seriously enough, but ourselves not at all. Bring thick skin and a broken microphone.',
    'features.friendship.title': 'Forced Friendship',
    'features.friendship.desc': 'At the end of the day, Broski is about the people. Terribly loud, geographically scattered, and bizarrely loyal people. We\'re a family, albeit highly dysfunctional.',
    'features.pvp.title': 'Extreme Combat',
    'features.pvp.desc': 'Fight to the death in the arena.',
    'features.events.title': 'Monthly Tournaments',
    'features.events.desc': 'Competitions with real prizes and eternal glory.',
    'features.streaming.title': 'Non-Stop Live',
    'features.streaming.desc': 'Follow our adventures live on Twitch.',
    'features.modding.title': 'Modded Servers',
    'features.modding.desc': 'Beyond vanilla, we explore new worlds.',
    'features.discord.title': 'Active Chat',
    'features.discord.desc': 'Our headquarters for coordination.',
    'features.redstone.title': 'Crazy Engineering',
    'features.redstone.desc': 'Complex circuits that nobody understands.',
    'features.survival.title': 'Hardcore Survival',
    'features.survival.desc': 'One life, a thousand ways to lose it.',
    'features.creative.title': 'Total Freedom',
    'features.creative.desc': 'Express your creativity without limits.',
    'features.lore.title': 'Group History',
    'features.lore.desc': 'Years of memes and unforgettable moments.',
    'features.future.title': 'New Projects',
    'features.future.desc': "What we're preparing for you.",
    'features.competitive.title': 'Competitive',
    'features.competitive.desc': 'Participate in tournaments and events with top players. Prove your worth and climb the rankings.',
    'features.community.title': 'Community',
    'features.community.desc': 'Join an active and passionate community. Find new friends and rivals to play with.',
    'features.rewards.title': 'Rewards',
    'features.rewards.desc': 'Win exclusive prizes and recognition for your performance. Every victory counts.',

    // TierList Page
    'tierlist.title': 'Competitive TierList',
    'tierlist.subtitle': 'Ranking of the best players by category',
    'tierlist.category.overall': 'Overall',
    'tierlist.category.ltms': 'LTMs',
    'tierlist.category.vanilla': 'Vanilla',
    'tierlist.category.uhc': 'UHC',
    'tierlist.category.pot': 'Pot PvP',
    'tierlist.category.nethop': 'Netherite Hop',
    'tierlist.category.smp': 'SMP',
    'tierlist.category.sword': 'Sword',
    'tierlist.category.axe': 'Axe',
    'tierlist.category.mace': 'Mace',
    'tierlist.category.crystal': 'Crystal',
    'tierlist.rank': 'Rank',
    'tierlist.player': 'Player',
    'tierlist.points': 'Points',
    'tierlist.region': 'Region',
    'tierlist.tier.ht1': 'HT1 - Elite',
    'tierlist.tier.lt1': 'LT1 - Pro',
    'tierlist.tier.ht2': 'HT2 - Advanced',
    'tierlist.tier.lt2': 'LT2 - Intermediate',
    'tierlist.tier.ht3': 'HT3 - Basic',
    'tierlist.tier.lt3': 'LT3 - Beginner',
    'tierlist.tier.ht4': 'HT4 - Novice',
    'tierlist.tier.lt4': 'LT4 - Learner',
    'tierlist.tier.ht5': 'HT5 - Rookie',
    'tierlist.tier.lt5': 'LT5 - Newbie',
    'tierlist.tier.unranked': 'Unranked',
    'tierlist.loading': 'Loading...',
    'tierlist.empty': 'No players in this category',
    'tierlist.empty.hint': 'Try another filter or go back to the global leaderboard to see all available players.',
    'tierlist.stats.total': 'Total Players',
    'tierlist.stats.top': 'Top Tier',
    'tierlist.stats.avg': 'Avg Points',
    'tierlist.cta.leaderboard': 'Explore',
    'tierlist.filter.mode': 'Ranking mode',
    'tierlist.filter.choose': 'Choose category',
    'tierlist.filter.hint': 'Scroll horizontally, switch discipline and the leaderboard instantly reorders by tier and points.',
    'tierlist.leaderboard.active': 'Active leaderboard',

    // Projects Page
    'projects.title': 'Our Projects',
    'projects.subtitle': 'Discover initiatives and content from the community',
    'projects.youtube.title': 'YouTube Channel',
    'projects.youtube.desc': 'Subscribe to our channel for videos, tutorials, and competition highlights.',
    'projects.twitch.title': 'Twitch Live',
    'projects.twitch.desc': 'Follow our live streams with events and community interaction.',
    'projects.discord.title': 'Discord Server',
    'projects.discord.desc': 'Join our Discord server to chat, find teams, and participate in events.',
    'projects.tiktok.title': 'TikTok',
    'projects.tiktok.desc': 'Watch our short videos with funny clips and epic moments.',
    'projects.visit': 'Visit',
    'projects.subscribe': 'Subscribe',
    'projects.join': 'Join',
    'projects.follow': 'Follow',
    'projects.hero.badge': 'BROSKI LABS',
    'projects.hero.stat.server': 'Server & SMP',
    'projects.controlsmp.featured': 'FEATURED',
    'projects.controlsmp.status': 'OFFLINE - SEASON 0',
    'projects.controlsmp.desc': 'Our main project inspired by the YouTuber series, with events and lore created by the community. Build, survive, betray.',
    'projects.controlsmp.countdown': 'GO TO COUNTDOWN',
    'projects.controlsmp.map': 'MAP SOON',
    'projects.wiki.title': 'Broski Wiki',
    'projects.wiki.desc': 'The official Broski encyclopedia where we document every event, member and madness that happened on the server.',
    'projects.wiki.progress': '100% COMPLETED',
    'projects.wiki.cta': 'READ THE WIKI',
    'projects.tools.title': 'Broski Projects',
    'projects.tools.desc': 'A collection of tools, websites and mods created by members to improve the gaming experience.',
    'projects.tools.repo': 'EXPLORE REPO',
    'projects.tools.mods': 'DOWNLOAD MODS',
    'projects.idea.badge': 'OPEN CALL',
    'projects.idea.title': 'Got a crazy idea?',
    'projects.idea.desc': 'We are always looking for new projects to integrate into the Broski ecosystem. Propose your idea on the dedicated page.',
    'projects.idea.cta': 'PROPOSE',

    // Social Page
    'social.title': 'Our Crew',
    'social.subtitle': 'Meet the members and staff of the community',
    'social.filter.all': 'All',
    'social.filter.founder': 'Founder',
    'social.filter.cofounder': 'Co-Founder',
    'social.filter.admin': 'Admin',
    'social.filter.mod': 'Mod',
    'social.member': 'Member',
    'social.rank': 'Rank',
    'social.discord': 'Discord',
    'social.youtube': 'YouTube',
    'social.twitch': 'Twitch',
    'social.description': 'Description',
    'social.status.online': 'Online',
    'social.status.offline': 'Offline',
    'social.info': 'INFO',
    'social.close': 'CLOSE',
    'social.crew.active': 'Active Crew',
    'social.channels': 'YouTube Channels',
    'social.streamers': 'Twitch Streamers',
    'social.card.member': 'Member Card',
    'social.card.whois': 'Who is {name}?',
    'social.card.links': 'links',
    'social.card.social': 'Social',
    'social.card.status': 'Status',
    'social.render.3d': '3D RENDER',
    'social.render.live': 'LIVE',
    'social.roster.selected': 'Selected roster',
    'social.roster.all': 'Full crew',
    'social.roster.hint': 'Tap a card to open the full dossier. Social buttons are always reachable without opening the panel.',

    // Wiki Page
    'wiki.title': 'Knowledge Base',
    'wiki.subtitle': 'Guides, tutorials, and community information',
    'wiki.hero.badge': 'OFFICIAL DOCUMENTATION',
    'wiki.hero.description': 'Welcome to the official documentation of the Broski Community. Here you can find everything you need to know about ??? SMP, the Tier List, our creators and how to become part of the community.',
    'wiki.nav.community': 'The Community',
    'wiki.nav.smp': '??? SMP',
    'wiki.nav.tierlist': 'Tier List',
    'wiki.nav.creators': 'Creators',
    'wiki.nav.faq': 'FAQ',
    'wiki.search.placeholder': 'Search the wiki...',
    'wiki.category.gettingstarted': 'Getting Started',
    'wiki.category.rules': 'Rules',
    'wiki.category.pvp': 'PvP',
    'wiki.category.faq': 'FAQ',
    'wiki.category.all': 'All Categories',
    'wiki.article.read': 'Read',
    'wiki.article.minutes': 'min read',
    'wiki.empty': 'No articles found',
    'wiki.back': 'Back to Wiki',
    'wiki.lastupdated': 'Last updated',

    // Wiki Content
    'wiki.community.title': 'The Community',
    'wiki.community.intro': 'is a group of Italian players united by their passion for Minecraft and the chaotic content we create together. We are an open community where everyone can join, participate and contribute to the activities we organize.',
    'wiki.community.discord.desc': 'The heart of the community. Voice channels active 24/7, events, announcements and where everything begins.',
    'wiki.community.smp.desc': 'Our anarchic Minecraft server where creators record their most iconic content.',
    'wiki.community.tierlist.desc': 'Competitive rankings across 11 different PvP categories. HT (High Tier) and LT (Low Tier).',
    'wiki.community.join.title': 'How to Join',
    'wiki.community.join.step1': 'Join our',
    'wiki.community.join.step2': 'Introduce yourself in the dedicated channel and read the rules',
    'wiki.community.join.step3': 'Actively participate in discussions and events',
    'wiki.community.join.step4': 'If you are a creator, contact the staff for possible collaborations',
    'wiki.smp.title': '??? SMP',
    'wiki.smp.intro': 'is the Minecraft server that gave life to the Broski Community. An anarchic server where creators record their content, create lore and build epic projects (that sometimes catch fire).',
    'wiki.smp.features.title': 'Features',
    'wiki.smp.features.java': 'Java Edition server',
    'wiki.smp.features.survival': 'Survival mode',
    'wiki.smp.features.events': 'Seasonal events',
    'wiki.smp.features.youtube': 'YouTuber integration',
    'wiki.smp.rules.title': 'Basic Rules',
    'wiki.smp.rules.nohack': 'No hacking or modified clients',
    'wiki.smp.rules.lore': 'Respect the existing lore',
    'wiki.smp.rules.collab': 'Collaborate with the community',
    'wiki.smp.rules.creator': 'Become a creator to access',
    'wiki.smp.status.title': 'Current Status',
    'wiki.smp.status.desc': 'Season 0 - The server is currently being prepared for the new season. Stay updated on Discord channels for opening dates.',
    'wiki.tierlist.intro': 'is the community competitive ranking system. Players are ranked based on their PvP skills across 11 different categories.',
    'wiki.tierlist.ht.desc': 'The best players, divided into 5 levels:',
    'wiki.tierlist.lt.desc': 'Developing players, divided into 5 levels:',
    'wiki.tierlist.combatrank.desc': 'Special titles based on total points:',
    'wiki.tierlist.categories.title': 'The 11 Categories',
    'wiki.tierlist.cta': 'Go to the Tier List',
    'wiki.creators.title': 'Creators',
    'wiki.creators.intro': 'The Broski Community includes several content creators who produce YouTube videos and Twitch streams, bringing ??? SMP lore and community activities to a wider audience.',
    'wiki.creators.youtube.desc': 'Creators publish videos about their ??? SMP adventures, community events and collaborative Minecraft series.',
    'wiki.creators.twitch.desc': 'Live gameplay streams, community interactions and special live events.',
    'wiki.creators.collab.title': 'Collaborations',
    'wiki.creators.collab.desc': 'Cross-creator events, collaborative videos and shared projects that enrich community content.',
    'wiki.creators.join.title': 'Want to Become a Broski Creator?',
    'wiki.creators.join.desc': 'If you have a YouTube or Twitch channel and want to join the official creators, join Discord and contact the staff. We evaluate collaborations with creators who share our passion for Minecraft and chaotic entertainment.',
    'wiki.faq.title': 'FAQ',
    'wiki.faq.q1': 'How can I join the community?',
    'wiki.faq.a1': 'Join our official Discord, introduce yourself in the dedicated channel and start actively participating. The community is open to all Italian Minecraft players.',
    'wiki.faq.q2': 'Is ??? SMP accessible to everyone?',
    'wiki.faq.a2': 'No, ??? SMP is a server reserved for official community creators. However, we organize events open to other community members as well.',
    'wiki.faq.q3': 'How does the Tier List work?',
    'wiki.faq.a3': 'The Tier List ranks players in 11 PvP categories. Each category has HT (High Tier, blue) and LT (Low Tier, red) ranks. OVERALL is automatically calculated as the average of all other ranks.',
    'wiki.faq.q4': 'Can I suggest changes to the site?',
    'wiki.faq.a4': 'Of course! We are always open to suggestions. Contact an admin on Discord or use the dedicated feedback channels.',
    'wiki.faq.q5': 'How are Tier List points assigned?',
    'wiki.faq.a5': 'Points depend on the tier: HT1/LT1 = 45-60 pts, HT2/LT2 = 20-30 pts, HT3/LT3 = 6-10 pts, HT4/LT4 = 3-4 pts, HT5/LT5 = 1-2 pts.',
    'wiki.faq.q6': 'Is there a minimum age to join?',
    'wiki.faq.a6': "We don't have a strict age limit, but we require maturity and respect for community rules. Behavior is more important than age.",
    'wiki.cta.title': 'Join Us',
    'wiki.cta.desc': 'The Broski Community is waiting for you. Join Discord, explore the Tier List, follow the creators and have fun with us!',
    'wiki.cta.discord': 'Join Discord',
    'wiki.cta.community': 'Explore the Community',

    // Login/Auth
    'auth.login.title': 'Login',
    'auth.login.subtitle': 'Sign in with your Broski account',
    'auth.login.discord': 'Sign in with Discord',
    'auth.login.google': 'Sign in with Google',
    'auth.login.or': 'or',
    'auth.login.email': 'Email',
    'auth.login.password': 'Password',
    'auth.login.remember': 'Remember me',
    'auth.login.forgot': 'Forgot password?',
    'auth.login.button': 'Sign In',
    'auth.login.noaccount': "Don't have an account?",
    'auth.login.register': 'Sign Up',
    'auth.logout.confirm': 'Are you sure you want to logout?',
    'auth.logout.yes': 'Yes, logout',
    'auth.logout.no': 'Cancel',

    // SignIn
    'signin.title': 'LOGIN',
    'signin.subtitle': 'Sign in to your Broski account',
    'signin.identifier': 'Username or Email',
    'signin.identifier_placeholder': 'e.g. Steve or steve@email.com',
    'signin.password': 'Password',
    'signin.password_placeholder': 'Your password',
    'signin.loading': 'Loading...',
    'signin.button': 'LOGIN',
    'signin.or': 'Or',
    'signin.create_account': 'CREATE ACCOUNT',

    // UnstableSmp
    'smp.badge': 'FEATURED SERVER',
    'smp.description': 'The ultimate Italian anarchic Minecraft server. Go watch the videos of the YouTubers who brought this world to life!',
    'smp.countdown_info': 'Countdown, map and season opening available soon',
    'smp.goto_countdown': 'GO TO COUNTDOWN',
    'smp.of_control': 'OF ??? SMP',

    // Countdown
    'countdown.title': 'COUNTDOWN',
    'countdown.days': 'DAYS',
    'countdown.hours': 'HOURS',
    'countdown.minutes': 'MINUTES',
    'countdown.seconds': 'SECONDS',
    'countdown.launched': 'LAUNCHED!',
    'countdown.finished': 'The season has started! See you on the server.',
    'countdown.mute': 'MUTE',
    'countdown.unmute': 'UNMUTE',

    // Idols
    'idols.badge': 'FROM ??? SMP',
    'idols.title': 'CREATOR WALL',
    'idols.description': 'Videos, epic moments and creators fueling the chaos: check out the channels and catch the latest content.',
    'idols.creator': 'CREATOR',
    'idols.latest_video': 'Latest Video:',
    'idols.watch_video': 'LATEST VIDEO',

    // Footer
    'footer.rights': 'All rights reserved',
    'footer.made': 'Made with',
    'footer.by': 'by the Broski community',
    'footer.links': 'Useful Links',
    'footer.contact': 'Contact',
    'footer.legal': 'Legal',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.disclaimer': 'NOT AN OFFICIAL MINECRAFT PRODUCT.',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.retry': 'Retry',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.create': 'Create',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.apply': 'Apply',
    'common.reset': 'Reset',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.submit': 'Submit',
    'common.close': 'Close',
    'common.open': 'Open',
    'common.more': 'More',
    'common.less': 'Less',
    'common.show': 'Show',
    'common.hide': 'Hide',
    'common.workingon': 'Seems like we\'re working here...',
    'common.gohome': 'GO TO THE HOME PAGE',

    // Admin Panel
    'admin.title': 'Admin Panel',
    'admin.subtitle': 'Manage news, tierlist and players',
    'admin.tab.news': 'NEWS',
    'admin.tab.tierlist': 'TIER LIST',
    'admin.news.title': 'News Management',
    'admin.news.new': 'NEW NEWS',
    'admin.news.edit': 'Edit News',
    'admin.news.create': 'New News',
    'admin.news.form.title': 'Title',
    'admin.news.form.category': 'Category',
    'admin.news.form.content': 'Content',
    'admin.news.form.icon': 'Icon (Material Symbol)',
    'admin.news.form.variant': 'Variant',
    'admin.news.form.variant.default': 'Default',
    'admin.news.form.variant.urgent': 'Urgent (Blue)',
    'admin.news.form.variant.event': 'Event (Secondary)',
    'admin.news.form.order': 'Order',
    'admin.news.form.active': 'Active',
    'admin.tierlist.title': 'TierList Management',
    'admin.tierlist.new': 'NEW PLAYER',
    'admin.tierlist.edit': 'Edit Player',
    'admin.tierlist.create': 'New Player',
    'admin.tierlist.form.ign': 'Minecraft IGN',
    'admin.tierlist.form.region': 'Region',
    'admin.tierlist.form.ranks': 'RANKS PER CATEGORY',
    'admin.tierlist.form.overall': 'OVERALL (auto)',
    'admin.tierlist.form.overall.desc': 'Calculated from the average of all categories',
    'admin.tierlist.points': 'points',
    'admin.tierlist.combatrank': 'Combat Rank',
    'admin.tierlist.save': 'SAVE',
    'admin.tierlist.cancel': 'CANCEL',
    'admin.players.title': 'Players',
    'admin.players.search': 'Search players...',
    'admin.players.edit': 'Edit',
    'admin.players.delete': 'Delete',
    'admin.save': 'Save',
    'admin.cancel': 'Cancel',
    'admin.delete': 'Delete',
    'admin.edit': 'Edit',
    'admin.actions': 'Actions',
    'admin.created': 'created',
    'admin.updated': 'updated',

    // 404 Page
    'notfound.message': "This page doesn't exist... maybe it was deleted, or maybe it never existed.",

    // Store
    'store.badge': 'BROSKI STORE',
    'store.title': 'MERCH COMING SOON',
    'store.description': 'Official Broski Community merch is on its way. Stay tuned for hoodies, tees, accessories and much more.',
    'store.wip': 'Work in Progress',
    'store.wip.desc': "We're preparing something special for you.",
    'store.notify': 'Follow us on Discord to know when we open!',
    'store.coming_soon': 'COMING SOON',
    'store.banner': 'Shipping across Europe • Premium Quality • Exclusive Designs',

    // Mods
    'mods.badge': 'BROSKI MODS',
    'mods.title': 'MODS & PLUGINS',
    'mods.subtitle': 'Download mods and plugins created by the Broski Community.',
    'mods.publish': 'Publish',
    'mods.my_mods': 'MY MODS',
    'mods.search': 'Search plugins...',
    'mods.sort_by': 'Sort by:',
    'mods.view': 'View:',
    'mods.results': 'results',
    'mods.no_results': 'No results',
    'mods.no_results.hint': 'Try changing the filters or search query.',
    'mods.followed_creators': 'Followed',
    'mods.saved_projects': 'Saved',
    'mods.back': 'BACK',
    'mods.projects': 'projects',
    'mods.no_followed': 'No followed creators',
    'mods.no_followed_hint': 'Follow creators from their project pages.',
    'mods.no_saved': 'No saved projects',
    'mods.no_saved_hint': 'Save projects you like from their pages.',
    'idea.back': 'BACK TO PROJECTS',
    'idea.badge': 'WILD IDEA',
    'idea.title': 'SUBMIT AN IDEA',
    'idea.subtitle': 'Got an idea for the community? Write it here and we\'ll read it!',
    'idea.field.title': 'IDEA TITLE',
    'idea.field.title_placeholder': 'e.g. Monthly PvP tournament with prizes',
    'idea.field.content': 'YOUR IDEA',
    'idea.field.content_placeholder': 'Describe your idea in detail...',
    'idea.field.rating': 'HOW WAS THE EXPERIENCE?',
    'idea.field.rating_desc': 'How much did you enjoy submitting an idea? (1-5 stars)',
    'idea.submit': 'SUBMIT IDEA',
    'idea.submitting': 'SUBMITTING...',
    'idea.error.login': 'You must be logged in.',
    'idea.error.title': 'Title is required.',
    'idea.error.content': 'Description is required.',
    'idea.error.rating': 'Please select a rating.',
    'idea.success.title': 'Idea submitted!',
    'idea.success.desc': 'Thanks for your contribution! Admins will review it soon.',
    'nav.my_ideas': 'My Ideas',
    'myideas.empty': 'You haven\'t submitted any ideas yet',
    'myideas.submit_first': 'SUBMIT YOUR FIRST IDEA',
    'mods.category': 'Category',
    'mods.game_version': 'Game version',
    'mods.loader': 'Loader',
    'mods.platform': 'Platform',
    'mods.show_all_versions': 'Show all versions',
    'mods.show_less': 'Show less',
    'mods.upload.title': 'NEW MOD',
    'mods.upload.subtitle': 'Fill in all fields and submit for review. An admin will approve your mod.',
    'mods.upload.info': 'Basic Information',
    'mods.upload.files': 'Files',
    'mods.upload.jar': '.JAR FILE',
    'mods.upload.jar.hint': 'Click to upload the .jar file',
    'mods.upload.icon': 'ICON',
    'mods.upload.icon.hint': 'Click to upload an icon',
    'mods.upload.screenshots': 'SCREENSHOTS',
    'mods.upload.screenshots.hint': 'Click to upload screenshots',
    'mods.upload.submit': 'SUBMIT FOR REVIEW',
    'mods.upload.submitting': 'UPLOADING...',
    'mods.upload.note': 'Your mod will only be visible to you and admins until approved.',
    'mods.detail.description': 'Description',
    'mods.detail.gallery': 'Gallery',
    'mods.detail.versions': 'Versions',
    'mods.detail.download': 'Download',
    'mods.detail.downloading': 'Downloading...',
    'mods.detail.compatibility': 'Compatibility',
    'mods.detail.platforms': 'Platforms',
    'mods.detail.environments': 'Supported environments',
    'mods.detail.tags': 'Tags',
    'mods.detail.creator': 'Creator',
    'mods.detail.details': 'Details',
    'mods.detail.published': 'Published',
    'mods.detail.updated': 'Updated',
    'mods.detail.size': 'Size',
    'mods.detail.not_found': 'Mod not found',
    'mods.detail.back': 'BACK TO MODS',
    'mods.detail.no_screenshots': 'No screenshots available.',
    'mods.my.title': 'MY MODS',
    'mods.my.subtitle': 'Manage your mods and check approval status.',
    'mods.my.empty': "You haven't uploaded any mods yet.",
    'mods.my.first': 'UPLOAD YOUR FIRST MOD',
    'mods.status.pending': 'IN REVIEW',
    'mods.status.approved': 'APPROVED',
    'mods.status.rejected': 'REJECTED',
    'mods.status.on_hold': 'ON HOLD',

    // Contacts
    'contacts.badge': 'REACH OUT',
    'contacts.title': 'CONTACTS',
    'contacts.response_time': 'Response Time',
    'contacts.response_desc': 'We generally respond within 24-48 hours. For urgent matters, the fastest way to reach us is through Discord. For collaborations or proposals, include a brief project description.',

    // Auth Terms
    'auth.terms.title': 'ACCEPT TERMS',
    'auth.terms.subtitle': 'To continue you must accept our updated terms.',
    'auth.terms.checkbox': "I accept the Terms of Service and Privacy Policy of the Broski Community.",
    'auth.terms.accept': 'ACCEPT AND CONTINUE',
    'auth.terms.error': 'You must accept the Terms of Service and Privacy Policy to continue.',
    'auth.terms.signup_error': 'You must accept the Terms of Service and Privacy Policy to sign up.',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('broski-language') as Language;
      return saved || 'it';
    }
    return 'it';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('broski-language', lang);
      document.documentElement.lang = lang;
    }
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  useEffect(() => {
    if (typeof window === 'undefined') return;

    const shouldSkipElement = (element: HTMLElement) => {
      return Boolean(
        element.closest(
          'script, style, noscript, textarea, input, option, select, code, pre, svg, .material-symbols-outlined, [data-no-translate]'
        )
      );
    };

    const translateNode = (node: Text) => {
      const parent = node.parentElement;
      if (!parent || shouldSkipElement(parent)) return;

      const currentText = node.textContent || '';
      const original = parent.dataset.originalText || currentText;
      const normalized = normalizeText(original);

      if (!normalized) return;

      if (!parent.dataset.originalText) {
        parent.dataset.originalText = original;
      }

      const nextText = language === 'en'
        ? automaticTranslations[normalized] || original
        : parent.dataset.originalText || original;

      if (node.textContent === nextText) return;

      if (language === 'en') {
        node.textContent = nextText;
      } else {
        node.textContent = nextText;
      }
    };

    const translatePage = () => {
      const walker = document.createTreeWalker(
        document.body,
        NodeFilter.SHOW_TEXT,
        {
          acceptNode: (node) => {
            const parent = node.parentElement;
            const text = normalizeText(node.textContent || '');
            if (!parent || !text) return NodeFilter.FILTER_REJECT;
            if (shouldSkipElement(parent)) {
              return NodeFilter.FILTER_REJECT;
            }
            if (!automaticTranslations[parent.dataset.originalText ? normalizeText(parent.dataset.originalText) : text]) {
              return NodeFilter.FILTER_REJECT;
            }
            return NodeFilter.FILTER_ACCEPT;
          },
        }
      );

      const textNodes: Text[] = [];
      while (walker.nextNode()) {
        textNodes.push(walker.currentNode as Text);
      }

      textNodes.forEach(translateNode);
    };

    translatePage();

    const observer = new MutationObserver(() => {
      translatePage();
    });

    observer.observe(document.body, {
      childList: true,
      subtree: true,
      characterData: false,
    });

    return () => observer.disconnect();
  }, [language]);

  const t = (key: string): string => {
    const currentTranslations = translations[language];
    const fallbackTranslations = translations.it;
    const translated = currentTranslations[key as keyof typeof currentTranslations] || fallbackTranslations[key as keyof typeof fallbackTranslations];
    if (translated) return translated;
    return key
      .split('.')
      .pop()
      ?.replace(/[-_]/g, ' ')
      .replace(/\b\w/g, (char) => char.toUpperCase()) || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
